require 'simplecov'
SimpleCov.start
require 'rspec'
require 'pry'
require './lib/stat_tracker'
require './lib/game'
require './lib/team'
require './lib/game_teams'
require './lib/game_statable'
require './lib/league_statable'
require './lib/season_statable'